document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <style>");
document.writeln("        .global-nav-wrapper {");
document.writeln("            width: 100%;");
document.writeln("            height: 44px;");
document.writeln("            background: rgba(0, 0, 0, 0.8);");
document.writeln("        }");
document.writeln("        .global-nav-wrapper-content {");
document.writeln("            width: 976px;");
document.writeln("            margin: auto;");
document.writeln("            height: 100%;");
document.writeln("            color: #f5f5f7;");
document.writeln("            display: flex;");
document.writeln("            justify-content: space-between;");
document.writeln("            font-size: 12px;");
document.writeln("            line-height: 44px;");
document.writeln("        }");
document.writeln("        .link-apple {");
document.writeln("            display: inline-block;");
document.writeln("            height: 44px;");
document.writeln("            width: 14px;");
document.writeln("            background-image: url(./svgs/apple.svg);");
document.writeln("        }");
document.writeln("        .link-search {");
document.writeln("            display: inline-block;");
document.writeln("            width: 15px;");
document.writeln("            height: 44px;");
document.writeln("            background-image: url(./svgs/search.svg);");
document.writeln("");
document.writeln("        }");
document.writeln("        .link-bag {");
document.writeln("            display: inline-block;");
document.writeln("            width: 13px;");
document.writeln("            height: 44px;");
document.writeln("            background-image: url(./svgs/bag.svg);");
document.writeln("");
document.writeln("        }");
document.writeln("        .global-nav-wrapper-content li {");
document.writeln("            cursor: pointer;");
document.writeln("            opacity: 0.8;");
document.writeln("            transition: opacity .3s cubic-bezier(0.25, 0.1, 0.25, 1);");
document.writeln("            font-family: SF Pro Text;");
document.writeln("            font-weight: 100;");
document.writeln("        }");
document.writeln("        .global-nav-wrapper-content li:hover {");
document.writeln("            opacity: 1;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <nav class=\'global-nav-wrapper\' id=\'global-nav\'>");
document.writeln("        <ul class=\'global-nav-wrapper-content\'>");
document.writeln("            <li>");
document.writeln("                <a class=\'link-apple\'></a>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'javascript:;\'>Store</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>Mac</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>iPad</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>iPhone</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>Watch</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>AirPods</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>TV & Home</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>Only on Apple</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>Accessories</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>Support</a></li>");
document.writeln("            <li>");
document.writeln("                <a class=\'link-search\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'link-bag\'></a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </nav>");
document.writeln("</body>");
document.writeln("</html>");